carlosperate/awesome-microbit

- README.md
The Lancaster University guide to the micro:bit runtime is itself a valuable collection of documentation for the more advanced micro:bit user. Although not strictly a teaching resource, it is resource that teachers and users may both want to use and doesn't fit directly in any of the other categories. I've included it here as a single link to their documentation.
> Add link to Lancaster University guide

- README.md
Tools for using the micro:bit (via MicroPython serial connection) with the Dyalog APL programming language on the Raspberry Pi.
> Add microbit for Dyalog APL on the Pi to programming tools

- README.md
Wrapper round CoreBluetooth to easily get Micro:Bit button and accelerometer data into applications running on OSX that accept OSC (e.g. Max/MSP, Supercollider, Processing)
> Added CBMicroBit, for piping Microbit -> OSC

- README.md
Hi,
[CodeSpace](https://make.firialabs.com) is a new tool for using MicroPython on the BBC micro:bit. This pull request appends it to the MicroPython editors list.
Thanks,
Chris
> Add CodeSpace to MicroPython editors list.

- README.md
Interface module for using the Pixy cam with the BBC micro:bit
```
```
> Add Pixy MicroPython Module

- README.md
Library for interfacing with an Aosong AM2320 temperature and humidity sensor over I2C.
```
```
> Add AM2320 MicroPython Library

- README.md
Library for quad 7-segment LED display modules using the TM1637 LED driver.
```
```
> Add TM1637 MicroPython Library

- README.md
Module to enable talking to MIDI devices on the BBC micro:bit.
```
```
> Add micro:bit MIDI to MicroPython Libs

- README.md
Lisp - An interpreter for the classic AI programming language for the BBC micro:bit.
Thanks to @technoblogy!
```
```
> Add Lisp to other micro:bit languages

- README.md
- correct "weather:bit" -> "moto:bit" in the item about "moto:bit"
N/A
```
```
> Fixing Wrong Name

- README.md
A MakeCode package with blocks that support Roger Wagner's MakerBit board including Serial MP3, I2C LCD 1602, and ultrasonic.
```
```
> Add MakerBit to MakeCode Packages

- README.md
A link to a project that allows you to configure your micro:bit to work as a Bluetooth Low Energy remote control for Spotify on macOS.
```
```
> Add 'BLE remote control for Spotify' to projects

- README.md
How to use a micro:bit as a Bluetooth remote for LibreOffice Impress presentations (as well as other use cases) on Linux using evemu to handle a virtual input device
```
```
> Add Remote control LibreOffice slides with a micro:bit to Projects

- README.md
Make code and C++  driver for SHT20, SHT21, SHT25 digital sensor, enabling the the micro:bit to obtain temperature and relative humidity from them.
- Not applicable, as this entry is for both C++ libraries and MakeCode packages
```
```
> Add to MakeCode and C++ libraries sections

- README.md
A MakeCode package and C++ library to calculate distances using a VL53L0X Time-of-Flight ranging sensor.
- Exception: Same repo for Mkecode package and C++ library.
```
```
> Add VL53L0X to MakeCode packages and C++ libs

- README.md
MakeCode package and C++ library for using the KY-040 rotary encoder.
- Exception: Same entry in both MakeCode and C++ libs
```
```
> Add KY-040 rotatory encoder to MakeCode Package and C++ Libs sections

- README.md
IL2C is a translator implementation of .NET intermediate language to C language, with C# and F# examples for the micro:bit.
```
```
> Add IL2C to other programming languages

- README.md
C++ library and MakeCode package to control the PCA9685, a 16-channel PWM controller, with included servo support.
- Exception: Same repo for both C++ lib and MakeCode package
```
```
> Add PCA9685 to MakeCode packages and C++ libraries

- README.md
Simple MicroPython library to control the SSD1306 display via I2C.
- Exception: Place together with all the other SSD1306 MicroPython libs
```
```
> Add another SSD1306 MicroPython package/module

- README.md
Adding NeoBit, an open source board that lets you hook up NeoPixel and DotStar LEDs to a BBC micro:bit, also contains a headphone jack and a couple of slide potentiometers for input. 
```
```
> Add NeoBit to Hardware section

- README.md
Touch sensing with the capacitive touch sensor controller MPR121 (while it belongs to the MakerBit family the packages works independently of a MakerBit board)
```
```
> Add MakeCode extension MakerBit-Touch

- README.md
Control the MAX7219 LED matrix display module with an 8x8 LED matrix.
```
```
> Add MAX7219 8x8 MakeCode Extension

- README.md
Mbed library for the HTU21D digital humidity and temperature sensor.
```
```
> Add HTU21D lib to Cpp section

- README.md
Generic PCA9685 driver, a 16-channel PWM controller. 
```
```
> Add PCA9685 to MakeCode packages.

- README.md
According to https://microbit.edublocks.org , the app is deprecated and is been replaced by app.edublocks.org.  Fix link accordingly
```
```
> Fix link to EduBlocks

- README.md
[Adafruit Motor Driver Board](https://github.com/vijairaj/pxt-adafruit-motor-driver) - Driver to control the DC motors on the Adafruit Motor Shield v1.
```
```
> Add Adafruit Motor Driver Board to MakeCode extension section.

- README.md
[ESP-01](https://github.com/51bit/esp01) - Control an ESP8266 module via serial AT commands.
```
```
> Add ESP-01 to MakeCode extensions.

- README.md
[Micropython-MakeCode compatible Radio](https://github.com/rhubarbdog/microbit-radio) - Class MakeRadio which includes all the functionality of the Micropyhton radio module, while being compatible with MakeCode blocks
```
```
> Add Micropython-MakeCode compatible Radio to MicroPython modules.

- README.md
[SFC SNES Gamepad](https://github.com/51bit/SFC) - Connect an SNES (Super Nintendo/Super Famicom) controller to the micro:bit.
```
```
> Add SFC SNES Gamepad to MakeCode Extensions section.

- README.md
[Jump Lead Adapter](https://www.thingiverse.com/thing:3919130) - 3D print part for the micro:bit to insert the male end of jumper cables to the edge connector.
```
```
> Add Jump Lead Adapter to 3D Printing section.

- README.md
[British Council micro:bit for Teachers](https://microbit.britishcouncil.org) - This course with interactive video learning and progress tracking will guide you through 12 modules to get to know the micro:bit and block code editor (needs sign-up). 
```
```
> Add British Council micro:bit for Teachers to Teaching section

- README.md
Add clarification for Espruino as I tried using Espruino on my v1.5 micro:bit but Espruino doesn't work with the LSM303AGR on the v1.5 micro:bit due to different I2C addresses. I [added an issue](https://github.com/espruino/EspruinoDocs/issues/537) however @gfwilliams hasn't fixed this due to low interest from the entire micro:bit community - I'll try and make a PR for the Micro:bit Educational Foundation's website if it's hosted on GitHub. Thanks! 
- [ x]  I have read and understood the [Contribution Guidelines](htps://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
```
```
> Add clarification for readme regarding Espruino

- README.md
[Board support crate for micro:bit](https://docs.rs/crate/microbit/) - Contains everything required to get started with the use of Rust to create firmwares for the BBC micro:bit board.
```
```
> Add Board support crate for micro:bit to Rust section.

- README.md
[Rust on the micro:bit 101](https://www.eggers-club.de/blog/2018/05/31/rust-on-the-microbit-101-part-1/) - How to get started using the board support crate and start programming the BBC micro:bit in Rust.
```
```
> Add Rust on the micro:bit 101 to Rust section.

- README.md
Espruino now has support for v1.5 accelerometer and magnetometer. There's a note added to the top of https://www.espruino.com/MicroBit to mention you need the newest firmware version to take advantage of it. Also seems worth mentioning Bluetooth LE as I believe it's one of the only things that actually supports proper Bluetooth Low Energy, including the ability to program wirelessly
- [*] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
- [*] I am making an individual pull request for each suggestion
- [*] I have used the correct spelling and capitalisation for `BBC micro:bit`, `micro:bit`, and `Micro:bit Educational Foundation` (resource title could be excluded if there is a good reason)
- [*] The …
> Update Espruino status & mention block-based programming

- README.md
[MAX31855](https://github.com/bremoran/microDriver_max31855) - Driver for the MAX31855 Thermocouple Amplifier.
```
```
> Add MAX31855 to MakeCode Extensions

- README.md
[Read a PS/2 keyboard on a BBC micro:bit](http://www.suppertime.co.uk/blogmywiki/2020/08/ps2-keyboard-microbit/) - Learning how PS/2 keyboards work, their serial communication, and how to connect them to a micro:bit.
```
```
> Add Read a PS/2 keyboard on a BBC micro:bit to Articles.

- README.md
[COMPX318 MicroBit Compiler](https://peer-compile.cms.waikato.ac.nz) - Upload a single source file to be compiled online with the DAL C/C++ toolchain and download the resulting hex file.
```
```
> C++: Add COMPX318 MicroBit Compiler.

- README.md
[Eclipse Instructions](https://www.seismicmatt.com/2018/05/04/eclipse-yotta-c-c-and-the-bbc-microbit/) - Setting up Eclipse with Yotta to build and debug with the BBC micro:bit.
```
```
> C/C++: Add Eclipse Instructions.

- README.md
[BBC micro:bit V2 battery pack holder](https://www.prusaprinters.org/prints/46067-bbc-microbit-v2-battery-pack-holder) - A multi-purpose battery pack holder for BBC microbit that can stand on its own, be clipped on lanyard, or with use of velcro strap used as wearable.
```
```
> 3D Printing: BBC micro:bit V2 battery pack holder.

- README.md
[Rust on the BBC micro:bit](https://blog.drogue.io/rust-and-microbit/) - How to get started using Rust and BLE on the micro:bit, exposing temperature data as a Bluetooth Environment Sensing Service, and publishing it to the Drogue Cloud via a Bluetooth gateway.
```
```
> Rust: Add Rust on the BBC micro:bit.

- README.md
[Sonic Pi OSC](https://github.com/RBilsland/pxt-sonicpiosc) - Send OpenSound Control (OSC) messages to Sonic Pi from a micro:bit using an ESP8266.
```
```
> MakeCode: Add Sonic Pi OSC extension

- README.md
[pyscrlink](https://github.com/kawasaki/pyscrlink) - A Scratch-link for Linux to connect Scratch 3.0 to Bluetooth devices such as the micro:bit.
```
```
> Scratch: pyscrlink.

- README.md
[HTU21D](https://github.com/ti-nspire/microbit-in-micropython-library-for-HTU21D-sensor) - Library to interface with a HTU21D digital humidity and temperature sensor.
```
```
> MicroPython: Add HTU21D library

- README.md
[nRF51 Radio](https://github.com/tipih/NRF51_Radio_library) - Arduino library based on the micro:bit DAL radio implementation.
```
```
> C/C++: Add nRF51 Radio library.

- README.md
[micro:bit Rust Demos](https://github.com/dtcristo/microbit-demos) - Multiple Rust language demos running on the BBC micro:bit.
```
```
> Rust: Add micro:bit Rust Demos.

- README.md
[microbitUh](https://github.com/microbit-foundation/microbit-universal-hex/) - TypeScript/JavaScript library to combine micro:bit Hex files into a Universal Hex that works in all versions of the micro:bit.
```
```
> JS: Add microbit Universal Hex library.

- README.md
[micro:bit Kicad Edge Connector](https://github.com/JordanElectronics/kicad-microbit-edge-connector) - BBC micro:bit Edge Connector component library and PCB footprint for Kicad.
```
```
> HW: Add Kicad edge connector part.

- README.md
[Combining micro:bit with TI calculators](https://education.ti.com/en/teachers/microbit) - Connect and programme the BBC micro:bit in Python with multiple TI calculator models.
```
```
> Python: Add Combining micro:bit with TI calculators.

- README.md
[blehid](https://github.com/bsiever/microbit-pxt-blehid) - Set up the micro:bit V2 as Bluetooth HID device, like a keyboard, mouse, or gamepad.
```
```
> PXT: Add blehid extension.

- README.md
[midi2ubit](https://github.com/63rabbits/midi2ubit) - Convert MIDI notes to notes-string for micro:bit. The notes-string can then be played using a MakeCode extention.
```
```
> Tools: Add midi2ubit.

- README.md
[dstemp2wire](https://github.com/bsiever/microbit-dstemp-2wire) - This extension allows the micro:bit to use the Dallas Semiconductor DS18B20 temperature sensor with just two wires (parasitic power mode).
```
```
> PXT Extenion: Add dstemp2wire, DS18B20 library.

- README.md
[HT16K33](https://github.com/mcauser/deshipu-micropython-ht16k33) - Library for the HT16K33 LED matrix driver in multiple configurations (16x8, 8x8 or 8x8x2).
```
```
> MicroPython: Restore HT16K33 library from mirror.

- README.md
[RGB LED Matrix](https://github.com/vhiribarren/microbit-led-matrix-lib-rust) - Rust project for the BBC micro:bit controlling a 64x32 matrix panel with some level shifters.
```
```
> Rust: Add RGB LED Matrix project.

- README.md
[MCP23017](https://github.com/CaptainCredible/pxt-MCP23017) - MakeCode driver for the MCP23017 16-Bit I2C I/O Expander.
```
```
> MakeCode: Add MCP23017 driver.

- README.md
[micro:bit MicroPython stubs](https://github.com/microbit-foundation/micropython-microbit-stubs) - Type stubs for MicroPython for micro:bit to support the editor autocompletion.
```
```
> Python Tools: Add micro:bit MicroPython stub.

- README.md
[micro:bit artwork tool](https://microbit.org/design-your-microbit/v2/) - Online tool to create a bitmap or vector image of the BBC micro:bit board with custom LED display and micro:bit colour configuration.
```
```
> 2D: Add micro:bit artwork tool.

- README.md
[DHT11](https://github.com/rhubarbdog/microbit-dht11) - Library for for the DHT11 temperature and humidity sensor over 1 wire.
```
```
> MicroPython: Add DHT11 library.

- README.md
[MPR121](https://github.com/rhubarbdog/microbit-mpr121-keypad) - Library for the MPR121 Capacitive Touch Sensor over I2C.
```
```
> MicroPython: Add MPR121 library.

- README.md
Changed MicroCode is a icon-based to MicroCode is an icon-based
- [ x ] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
- [ x ]  I am making an individual pull request for each suggestion
- [ x ] I have used the correct spelling and capitalisation for `BBC micro:bit`, `micro:bit`, and `Micro:bit Educational Foundation` (resource title could be excluded if there is a good reason)
- [ x ] The content linked is in English, or it contains an English translation
- [ x ] I have added the new entry to the bottom of its the category
- [ x ] I have used the following format:
```
> Fixed the grammatical error in the readme file

- README.md
[Dance Detector](https://projects.raspberrypi.org/en/projects/dance-detector/) - Use CreateAI and micro:bit to train a Machine Learning model to identify your dance moves.
```
```
> Machine Learning Resources & Projects: Dance Detector.
