README.md
=> Add Grok Learning to the teaching resources section.

README.md
* Add micro:bit and Bluetooth playlist to videos 		
* Add CAD Resources to Miscellaneous 		
* Add micro:bit-o-matic to miscellaneous
=> Add BT playlist, CAD resources and micro:bit-o-matic

README.md
* Move micro:bit blue to the apps section 		
* Add bitty software apps 		
* Move official apps from tools to apps
=> Move mobile apps to the apps section, add bitty apps

README.md
Includes:
* micro:bit IoT In C
* BBC micro:bit - 35 Touch Develop & MicroPython Projects
*    Programming with MicroPython
=> Add books section

README.md
* Add A4 folder holder to 3D printer section
* Add mibot drawing robot to 3D printing section
=> Add 3d printin models

README.md
I added the link to my 8x8 Led matrix library and added indications to avoid confusion with the 7-segment one
=> add 8x8 Matrix led library

README.md
Adding Lorraine Underwood Little Bug Bit. Thanks @PragmaticPhil!
=> Add Little Bug Bit to Projects section

README.md
* KY-040 rotary encoder
* Invent robot
* Robobit
* ubirch NB-IoT
* CCS811 Air Quality Sensor
=> Add 5 MakeCode packages

README.md
* DS1307
* HT16K33 
* HoneyBit
=> Add 3 MakeCode packages

README.md
Networking with the micro:bit
micro:bit in Wonderland
=> Add eBooks section with 2 new entries

README.md
* micro:bit Hovercraft
* ZIP Halo Compass
=> Add 2 projects

README.md
Also remove ebooks section as there isn't enough entries (Alice is now a printed book as well).
=> Add Beginning BBC micro:bit book 

README.md
Kitronik University - A varied collection of micro:bit resources by Kitronik.
```
```
=> Add Kitronik University to Article collection

README.md
Learn how to use the micro:bit's built-in accelerometer and magnetometer.
```
```
=> Add the Using the Built-in Sensors Article

README.md
Are you a teacher who wants to use micro:bit in your classroom, but doesn't know where to start? We'll show you how!
```
```
=> Add Hackster micro:bit Basics for Teachers

README.md
Free resource to help parent's get actively involved in helping their children learn how to code, even with no prior coding experience. 
```
```
=> Adding Parent's Complete Guide To The micro:bit

README.md
Collection of Raspberry Pi and micro:bit projects from the Raspberry Pi Foundation
```
```
=> Add Raspberry Pi micro:bit Projects collection

README.md
A Linux application which interacts with the BBC micro:bit to give hand prothesis users the ability to control their desktop computer using gestures. 
```
```
=> Add OpenGestureControl to Projects section

README.md
=> BBC micro:bit composer

README.md
Circuit and code to display an audio spectrum bar chart on the BBC micro:bit.
```
```
=> Add micro:bit spectrum to Projects

README.md
Play the classic Pong game on a TV - using BBC Microbits as paddles, Bluetooth also supported
```
```
=> micro:bit TVPong to Projects

README.md
Module for the MB1013 ultrasonic sensor controlled via UART.
```
```
=> Add MB1013 to MicroPython Libraries

README.md
Library for 10 segment LED bar graph modules using the MY9221 LED driver.
```
```
=> Add MY9221 MicroPython Library.

README.md
Library for interfacing with an Aosong DHT12 temperature and humidity sensor over I2C.
```
```
=> Add DHT12 MicroPython Library

README.md
Adding to project collections Hackaday.io (collaborative hardware development community) projects using the micro:bit.
```
```
=> Add Hackaday.io to Project Collections section

README.md
Adding micro:mag , the unofficial micro:bit community magazine.
```
```
=> Add micro:mag to Miscellaneous section

README.md
A micro:bit MicroPython class to control the Kitronik motor driver board.
```
```
=> Add Kitronik Motor Driver Board MicroPython module

README.md
A link to a list with all the micro:bit blog post articles posted in Maker.io, a playground for makers.
```
```
=> Add Maker.io micro:bit blog posts to Article Collections

README.md
- [Read micro:bit data from Linux via Bluetooth (BLE)](https://github.com/alcir/microbit-ble) - Random notes and examples about micro:bit BLE and Linux.
Random notes and examples about micro:bit BLE and Linux.
```
```
=> Add Read micro:bit data from Linux via Bluetooth (BLE) article

README.md
A visual programming language inspired by Scratch that runs right inside microcontroller boards such as the micro:bit. 
```
```
=> Add MicroBlocks to Visual Programming section

README.md
A slim, nice looking, and functional snap-together case that protects all sides and corners.
```
```
=> Add BBC micro:bit Case V2 to 3D Printing section

README.md
All the micro:bit projects posted in Maker.io, a playground for makers.
```
```
=> Add Maker.io micro:bit projects to Project Collections section

README.md
An extensive project to examine Stirling engine operation and performance. A micro:bit is used to create a custom keyboard and LCD interface that communicates with other parts of the project.
```
```
=> Add Stirling Blue to Projects section

README.md
A portable game console based on the micro:bit board. It features a 128x64 monochrome OLED screen, six buttons, a buzzer for sound, and a 2xAAA battery holder. 
```
```
=> Add Micro:Gamer to Projects

README.md
MakeCode package to control the BMP085 or BMP180 pressure and altitude sensors.
```
```
=> Add BMP085 sensor to MakeCode packages

README.md
A REPL client for MicroPython running on the BBC micro:bit.
```
```
=> Add MicroREPL to Python programming tools

README.md
Otto chassis for the microbit to make a bidepad robot with a robitbit accessory.
```
```
=> Add Otto Robot to 3D Printing section

README.md
TinyGo is a project to bring Go to microcontrollers and small systems, with out-of-box support for the BBC micro:bit. 
```
```
=> Add TinyGo to other programming languages

README.md
micro:bit-inspired fan art made with "Make 8 Bit Art"
```
```
=> Add Pixel Art to 2D design section

README.md
Swift Playgrounds is an app for the iPad that helps teach people to code in the Swift language using interactive 'books'. This book interacts with the micro:bit wirelessly, helping you to learn the fundamentals of code while having fun with your micro:bit!
```
```
=> Add Official Swift playgrounds to Mobile Apps section

README.md
A multi-device coding canvas for block-based programming that connects with BLE devices via Chrome Web Bluetooth.
```
```
=> Add Workbench to Visual Programming section

README.md
An inexpensive and easy to build device to perform pressure measurements and demonstrate Boyle's law with the micro:bit and BMP280 pressure/temperature sensor. 
```
```
=> Add "Measure pressure with your micro:bit" to Articles section

README.md
A multiplayer snake game on Android, controlled with micro:bits via Bluetooth.
```
```
=> Add micro:bit Slither to Mobile Apps

README.md
Turning a BBC micro:bit into a test instrument by displaying all the sensor readings on an LCD and packaging it into a 3D printed box.
```
```
=> Add µBOSS to Projects section

README.md
The default program running on a brand new micro:bit.
```
```
=> Add OOB program to Miscellaneous section

README.md
A line follower chassis for the micro:bit.
```
```
=> Add micro:bit Tracking Car to 3D Printing section

README.md
Program BBC Micro:bit with mbed OS and remotely send data to cloud by utilizing BLE to smartphone/PC IoT cloud gateway.
```
```
=> Add IoT Cloud Access with Micro:bit over BLE for Remote Sensing Article

README.md
This is a simple add-on to the micro:bit and bit:booster (http://lectrify.it/bitbooster) that makes a simple walking robot using two continuous servos.
```
```
=> Add Walking Robot V1 to 3D printing section

README.md
Blog posts and articles about micro:bit from DF Robot.
```
```
=> Add DF Robot micro:bit blog section to Article collections section

README.md
Embedded IDE with support for the micro:bit using the Arduino or Mbed software stack.
```
```
=> Add PlatformIO to C/C++ Editors section

README.md
ElecFreaks collection of experiments, tutorials and material for the micro:bit.
```
```
=> Add ElecFreaks Learn to Article Collections section

README.md
DIY 3D Virtual Reality System that uses two micro:bits for head and hand orientation tracking.
```
```
=> Add DIY 3D Virtual Reality System to Projects section

README.md
A Swift Playground Book that introduces computer fundamentals in a visual way, it allows you to enter machine code or assembly and see how it executes and how the micro:bit registers are affected.
```
```
=> Add Micro:bit Explorer to Apps section

README.md
A gesture controlled Robot Arm Buggy using the micro:bit accelerometer and radio.
```
```
=> Add Robot Arm Rover to Projects section

README.md
A  chassis for a sumo robot
```
```
=> Add Humbot mi:sumo robot to 3D Printing section

README.md
A constantly updated list of accessories for the micro:bit.
```
```
=> Add Accessory Guide to Miscellaneous section

README.md
Guide to create an inexpesensive robot, easily assembled from a set of off the shelf parts.
```
```
=> Add Inexpensive Remote Controlled Robot to Projects section

README.md
=> add colorbit pxt extension

README.md
Collection of videos explaining the basics on how different hardware components work
```
```
=> Add Behind the MakeCode Hardware to Videos section

README.md
Play mp3 files with a DFPlayer mini module.
```
```
=> Add to dfplayer to MakeCode extensions

README.md
Wind, seismic, and temperature data monitoring from remote micro:bits.
```
```
=> Add Natural Disaster Sensor to Projects section

README.md
Based on the micro:bit, it provides everything you need to sniff, jam and hijack Bluetooth Low Energy devices. 
```
```
=> Add BtleJack to Miscellaneous section

README.md
Collection of utility blocks and functions to do things like rounding numbers and convert between decimal and hex.
```
```
=> Add Smart Tools to MakeCode Extensions.

README.md
A rear bike light with a Kitronik Zip Tile (8x8 RGB LED matrix) and 3D printed case.
```
```
=> Add Bike Light to Projects section.

README.md
Update URL for micro:bit uploader, a windows application that monitors your Downloads folder and flashes any new programs to the micro:bit.
* Link update
```
```
=> Update URL for the micro:bit Uploader

README.md
Two laser cut boxes, one for 10 micro:bits and another for 20.
```
```
=> Add Laser Cut Box to 3D Printing section

README.md
How to build an IoT “Pill Reminder” device to remind the patient to take their pills and update their status in Google Sheets.
```
```
=> Add IoT Pill Reminders to Projects

README.md
Practical science and engineering projects with the micro:bit, explore physical properties with cool experiments.
```
```
=> Add Saturday Science & BBC micro:bits to Project Collections.

README.md
Using micro:bit as control board and very simple 3D design, you can easy to assembly and program the biped robot.
```
```
=> Add Shiun robot to 3D Printing section.

README.md
Collection of videos explaining how to use the micro:bit features with MicroPython.
```
```
=> MicroPython for micro:bit Workshop to Videos section.

README.md
Arabic Community of Micro:bit users
=> Add arabic community

README.md
A  Tutorial explaining how to implement a basic multiplayer game on the BBC micro:bit with the following features:
- A simple interface
- Low-latency between button presses and screen updates
- A flexible number of participants
- Easy control over the game using a master remote ("root") device
```
```
=> Add Network Rivalry to Articles section.

README.md
Adds the beta versions of the MakeCode and Python editor.
```
```
=> Add links to the beta editors.

README.md
Adds Events sections and micro:bit Live 2019.
```
```
=> Add Events section.

README.md
Use an RGB matrix and a micro:bit to display the time with an awesome game of PONG. Made with love and TinyGo.
```
```
=> Add TinyGo Pong Clock to Projects section

README.md
3D models using a Power Board for the BBC micro:bit.
```
```
=> Add miniPOW models to 3D Printing section.

README.md
A desktop application to program the hardware devices, like the micro:bit, with blocks, Python, or the C language.
```
```
=> Add Mind+ to Visual Lang section.

README.md
Desktop application supporting block-based and Python-based programming on multiple hardware platforms, including the micro:bit.
```
```
=> Add mBlock 5 to Visual Langs section.

README.md
Controller for KeiganMotor KM-1 Series, an all-in-one brushless gearless electric motor module
```
```
=> Add KeiganMotor to MakeCode Extensions section.

README.md
A tablet-based programming option for the Hummingbird, including the micro:bit version.
```
```
=> Add BirdBlox to Mobile Apps section.

README.md
Creating micro:bit circuit boards in timber.
```
```
=> Add Circuit Lumber Punking to Articles section.

README.md
A 3D printed pinball machine with one or more micro:bits controlling it.
```
```
=> Add micro:bit pinball to 3D Printing section.

README.md
Connect your micro:bit to the Internet via WiFi network.
```
```
=> Add WiFi:bit to MakeCode extensions section.

README.md
Port for the microbit from the Arduino port of Tiny BASIC.
```
```
=> Add Tiny BASIC to Other micro:bit Languages section.

README.md
Official guide to create your own MakeCode extensions.
```
```
=> Add How to Build MakeCode Extensions entry

README.md
An introduction on how you can exchange information between a micro:bit and a Raspberry Pi using Bluetooth Low Energy (BLE). 
```
```
=> Add micro:bit <-> Raspberry Pi to Articles section.

README.md
Web Bluetooth library implementing the micro:bit Bluetooth Profile.
```
```
=> Add microbit-web-bluetooth to JS Libs section.

README.md
RAK811 Python library for use with LoRa pHAT & MicroBIT Node.
```
```
=> Add RAK811 to MicroPython Libraries section.

README.md
Collection of short videos showing how to use micro:bit MakeCode blocks and features.
```
```
=> Add Grade 10 micro:bit Tutorials to Videos section.

README.md
Stand that holds 14 micro:bits and battery packs.
```
```
=> Add micro:bit class rack to 3D Printing section.

README.md
Web Components for all the micro:bit features exposed via BLE.
```
```
=> Add microbit-web-components to JS Libs section.

README.md
I2C driver for Infra Red Thermometer MLX90614.
```
```
=> Add MLX90614 to MakeCode Extensions section.

README.md
Create a speed trap for toy cars with three micro:bits, torches, radio and REPL in Python.
```
```
=> Add Racing Car Timing Gate to Projects section.

README.md
Create a micro:bit web server via AT commands to an ESP8266 which can respond to web browser requests over WiFi.
```
```
=> Add WiFi Web Server on BBC micro:bit and ESP-01 Article

README.md
Walking through the steps for creating your own BBC micro:bit IoT device connected to the Sigfox network.
```
```
=> Add Connect BBC micro:bit to Sigfox to Articles section.

README.md
Sending and plotting sensor data to the thethings.iO via Sigfox network.
```
```
=> Add Visualising BBC micro:bit sensors with thethings.iO to Articles section.

README.md
Collection of 5-minute micro:bit makes, one for  each day of March 2019.
```
```
=> Add micro:bit Month Of Making to Article Collections section.

README.md
Basic lessons on programming with a BBC micro:bit in Python.
```
```
=> Add micro:bit Lessons to Teaching Resources section.

README.md
[Robot Unicorn](https://github.com/helenleigh/robot-unicorn) - Gesture controlled robot unicorn made of cardboard, glitter, a 3D printed horn, and micro:bits.
```
```
=> Add Robot Unicorn to Projects section.

README.md
[The Christmas Joy Spreading Machine](https://www.hackster.io/balearicdynamics/the-christmas-joy-spreading-machine-3d3559) - Project inside a box representing a metaphor of the most popular Christmas symbols. Maybe it's a bit distopyc but it moves, lights and reacts to music.
```
```
=> Add The Christmas Joy Spreading Machine to Projects section.

README.md
[micro:bit Guitar](https://www.kitronik.co.uk/blog/microbit-guitar-noise-pack-inventors-kit/) - A micro:bit guitar using the Noise Pack Add-on for the Kitronik Inventors Kit.
```
```
=> Add micro:bit Guitar to Projects section.

README.md
- [ . ] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
- [ . ] I am making an individual pull request for each suggestion
- [ . ] I have used the correct spelling and capitalisation for `BBC micro:bit`, `micro:bit`, and `Micro:bit Educational Foundation` (resource title could be excluded if there is a good reason)
- [ . ] The content linked is in English, or it contains an English translation
- [ . ] I have added the new entry to the bottom of its the category
- [ . ] I have used the following format:
```
```
=> Add TCS3200 MakeCode extension

README.md
- [ . ] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
- [ . ] I am making an individual pull request for each suggestion
- [ . ] I have used the correct spelling and capitalisation for `BBC micro:bit`, `micro:bit`, and `Micro:bit Educational Foundation` (resource title could be excluded if there is a good reason)
- [ . ] The content linked is in English, or it contains an English translation
- [ . ] I have added the new entry to the bottom of its the category
- [ . ] I have used the following format:
```
```
=> Add IR makecode extension

README.md
- [ . ] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
- [ . ] I am making an individual pull request for each suggestion
- [ . ] I have used the correct spelling and capitalisation for `BBC micro:bit`, `micro:bit`, and `Micro:bit Educational Foundation` (resource title could be excluded if there is a good reason)
- [ . ] The content linked is in English, or it contains an English translation
- [ . ] I have added the new entry to the bottom of its the category
- [ . ] I have used the following format:
```
```
=> Add DHT11/DHT22 makecode extension

README.md
- [ . ] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
- [ . ] I am making an individual pull request for each suggestion
- [ . ] I have used the correct spelling and capitalisation for `BBC micro:bit`, `micro:bit`, and `Micro:bit Educational Foundation` (resource title could be excluded if there is a good reason)
- [ . ] The content linked is in English, or it contains an English translation
- [ . ] I have added the new entry to the bottom of its the category
- [ . ] I have used the following format:
```
```
=> Add ESP8266/ThingSpeak makecode extension

README.md
[How to connect your Mini.mu to PureData](https://vulpestruments.com/2018/11/21/how-to-connect-your-mini-mu-to-puredata/) - Connecting the micro:bit to PureData (visual programming language to crate interactive computer music) via radio and serial MIDI
```
```
=> Add How to connect your Mini.mu to PureData to Articles section.

README.md
[Little Bird How To Guides](https://www.littlebird.com.au/a/how-to#micro-bit) - Detailed tutorials showing how to use a wide range of sensors and accessories with the micro:bit.
```
```
=> Add Little Bird How To Guides to Article Collection section.

README.md
[micro:bit Hand Controller](https://www.thingiverse.com/thing:3728487) - Nunchuck style single-hand controller for a micro:bit with an external thumb joystick and two buttons
```
```
=> Add Hand Controller to 3D Printed section.

README.md
[micro:bit to Firebase](https://www.youtube.com/playlist?list=PLGYgoZPmYyek0eIEfVWyt3nK_J8iZ4OBP) - Send data from a BBC micro:bit to Google’s Firebase cloud database with a Python script. Retrieve the data and  create a simple IoT demo model.
```
```
=> Add micro:bit to FireBase to Videos section.

README.md
[Hardware Simulation with QEMU](https://www.qemu.org/2019/05/22/microbit/) - micro:bit emulation support is available from QEMU 4.0 onwards and can be used for low-level software testing and development. 
```
```
=> Add Hardware Simulation with QEMU to Miscellaneous section.

README.md
=> Add CodeMao Kitten Editor to Visual section.

README.md
[BBC micro:bit Recipes](https://www.apress.com/gp/book/9781484249123)
```
```
=> Add BBC micro:bit Recipes to Books section.

README.md
[WalkerBot:bit](https://www.thingiverse.com/thing:2746171) - Two servo walking robot controlled by a BBC micro:bit.
```
```
=> Add WalkerBot:bit to 3D Printing section.

README.md
[Scratch micro:bit Tutorials](https://www.youtube.com/playlist?list=PLSgUBfi51uldOnJU11lVkViTZBi0rE30L) - Tutorials and project ideas for the micro:bit with Scratch.
```
```
=> Add Scratch micro:bit Tutorials to Videos section.

README.md
[Gesture controlled lamp](https://manoj.ninja/articles/2019/09/19/2019-building-a-gesture-controlled-lamp) - Building a colourful 3D printed lamp with the BBC micro:bit that responds to gestures.
```
```
=> Add Gesture controlled lamp to Projects section.

README.md
[micro:bit Magic Wand](https://www.instructables.com/id/Microbit-Magic-Wand-Beginner/) - This project uses two micro:bit, a few small electronic parts, and some everyday objects from around the house to create our very own magical wand.
```
```
=> Add Magic Wand to Projects section

README.md
[Micro:bit for Mad Scientists](https://nostarch.com/microbitformad) - The 30 simple projects and experiments in this book will show you how to use the micro:bit to build a secret science lab, as you learn basic coding and electronics skills.
```
```
=> Add Micro:bit for Mad Scientists to Books section.

README.md
Added another DS18B20 sensor package for makecode
Another DS18B20 sensor package for makecode. This one supports multiple sensors. Someone else confirmed that it works, even though it is alpha at the moment.
```
```
=> Add DS18B20 sensor package to Makecode Extensions

README.md
add DFRobot DS18B20 sensor package for makecode
DFRobot DS18B20 temperature sensor package for makecode
```
```
=> Add DFRobot DS18B20 to MakeCode extensions

README.md
=> Add MicroBike to Projects section

README.md
[Pimoroni Education](https://edu.pimoroni.com/tag/microbit/) - Educational resources with the micro:bit from Pimoroni.
```
```
=> Add Pimoroni Education to Teaching Resources section.

README.md
=> Add LightBit to Projects section

README.md
[Arm School Program Resources for Schools](https://www.arm.com/resources/education/schools/content) - A suite of teaching and learning resources to help teachers deliver engaging and inspirational lessons in Computing (K-12).
```
```
=> Add Arm School Program Resources for Schools to Teaching Resources.

README.md
[Gamer Case](https://www.prusaprinters.org/prints/20112-gamer-case-for-bbc-microbit) - A gamer case for your BBC micro:bit that is easy to print, handle and can attach the battery box at the back.
```
```
=> Add Gamer Case to 3D Printing section.

README.md
[Connected Flowerpot](https://www.instructables.com/id/Connected-Flowerpot-by-Microbit/) - 3D printed flowerpot that fist a micro:bit to detect soil moisture and display its status in an RGB LED ring.
```
```
=> Add Connected Flowerpot to Projects section.

README.md
[Voice Controlled Robot Car](https://www.hackster.io/H0meMadeGarbage/voice-controlled-robot-car-54faef) - Robot car controlled by voice commands using Amazon Alexa, Node-RED and micro:bit.
```
```
=> Add Voice Controlled Robot Car to Projects section.

README.md
[ChibiOS](https://github.com/ChibiOS/ChibiOS-Contrib) - A complete development environment for embedded applications including RTOS, a HAL, peripheral drivers, support files, and tools. 
```
```
=> Add RTOS section w/ ChibiOS entry.

README.md
- [Mynewt](https://github.com/apache/mynewt-core) - Open-source operating system for tiny embedded devices. Its goal is to make it easy to develop applications for microcontroller environments where power and cost are driving factors.
- [RIOT](https://riot-os.org/api/group__boards__microbit.html) - A friendly, real-time, multi-threading operating system that supports a range of devices that are typically found in the Internet of Things (IoT).
- [Zephyr](https://docs.zephyrproject.org/latest/boards/arm/bbc_microbit/doc/index.html) - A scalable real-time operating system (RTOS) supporting multiple hardware architectures, optimized for resource constrained devices, and built with security in mind.
```
- [Resource Title](link) - …
```
=> Add Mynewt, RIOT, and Zephyr to RTOS section

README.md
[MakeCode Forum](https://forum.makecode.com/c/microbit/11)
```
```
=> Add MakeCode Forum to Community section.

README.md
[Obstacle Detecting White Cane](https://www.instructables.com/id/Obstacle-Detecting-White-Cane/) - A warning system for unpredictable obstacles for those who are visually impaired.
```
```
=> Add Obstacle Detecting White Cane to Projects section

README.md
[Using micro:bit and MakeCode with Data Streamer](https://docs.microsoft.com/en-us/microsoft-365/education/data-streamer/using-microbit-and-makecode) - How to use the MakeCode to write a simple program that sends live data from the BBC micro:bit to Microsoft Excel using the Microsoft Data Streamer add-in.
```
```
=> Add Using micro:bit and Make Code with Data Streamer article.

README.md
[Cutebot](https://github.com/Krakenus/microbit-cutebot-micropython) - Library providing functions to work with Cutebot kit for BBC micro:bit.
```
```
=> Add MicroPython library for Cutebot kit

README.md
- [3D Rendering on a Children's Toy](https://blog.scottlogic.com/2020/03/03/microbit-raytracer.html) - Implementing a ray tracer, an algorithm which simulates light rays to render a 3D scene, to render a pyramid in the micro:bit display.
```
```
=> Add 3D Rendering on a Children's Toy to Articles section.

README.md
[The Learning Circuit](https://www.element14.com/community/community/element14-presents/thelearningcircuit/tags#/?tags=learning%20circuit+microbit) - Element14 video series to learn about basic electronics. Some of the episodes cover different ways to learn and explore with the BBC micro:bit.
```
```
=> Add The Learning Circuit to Video section.

README.md
[The ThreadBoard: micro:bit E-Textile Prototyping Board](https://www.instructables.com/id/The-ThreadBoard-Microbit-E-Textile-Prototyping-Boa/) - Developing a tool that will adapt to the unique set of constraints that e-textile creators face when fabricating an e-textile project.
```
```
=> Add The ThreadBoard: micro:bit E-Textile Prototyping Board  to Articles.

README.md
[micro:bit Quiz System](http://weddell.co.uk/computing/microbit-quiz-system/) - A wireless LED quiz button system with sound.
```
```
=> Add micro:bit Quiz System to Projets

README.md
- [Online Learning with MakeCode](https://makecode.com/online-learning) - A list of helpful resources, including live video streams, that students can access to continue their computing education outside the classroom now that many schools are closed.
```
```
=> Add Online Learning with MakeCode to Videos section.

README.md
[Creative Coding with micro:bit](https://www.youtube.com/playlist?list=PLIRQWQAcfF037nji2jK6iiafMLubgJqUh) - Creative activities with the micro:bit from Kids Code Jeunesse.
```
```
=> Add Creative Coding with micro:bit to Videos.

README.md
[DIY Educational micro:bit Robot](https://www.instructables.com/id/DIY-Educational-Microbit-Robot/) - Building a relatively accessible, capable and cheap robot. Two variants provided with different sensorrs and example code for MakeCode and MicroPython.
```
```
=> Add DIY Educational micro:bit Robot to Projects.

README.md
[MIDI CC Wireless Controller](https://www.instructables.com/id/Microbit-Midi-CC-Wireless-Controller/) - A wireless MIDI CC controller, allowing you to use your micro:bit as a MIDI controller and connect it to your favourite music production software.
```
```
=> Add MIDI CC Wireless Controller to Projects section.

README.md
=> Add DS3231 to MakeCode extensions section.

README.md
[Vittascience](https://vittascience.com/microbit/) - MicroPython block programming and built-in simulator for the micro:bit.
```
```
=> Add Vittascience to Visual Programming section.

README.md
[Device Simulator Express](https://marketplace.visualstudio.com/items?itemName=ms-python.devicesimulatorexpress) - Visual Studio Code extension with a micro:bit simulator, debugger and serial terminal.
```
```
=> Add Device Simulator Express to MicroPython Editors.

README.md
[micro:bit USB Grapher](https://github.com/bsiever/microbit-usb-grapher) - A web page using WebUSB to graph, manipulate, and save data collected on the micro:bit.
```
```
=> Add micro:bit USB Grapher to Miscellaneous

README.md
[MicroRust](https://droogmic.github.io/microrust/) - Discover the world of microcontrollers through Rust on the BBC micro:bit.
```
```
=> Add MicroRust to Rust section.

README.md
[MakeCode Offline App](https://makecode.microbit.org/offline-app) - Stand alone offline app (note that MakeCode in your browser also works offline).
```
```
=> Add MakeCode Offline App.

README.md
[Video Tutorials for micro:bit](https://www.youtube.com/watch?v=-HUD_96vvJA&list=PLS9qLR8VoFA5jr14vzjJwqZ5DsBLFzuYn) - A playlist of video tutorials by Geek Tutorials, walking through a lot of the micro:bit features.
```
```
=> Add Video Tutorials for micro:bit to Videos section.

README.md
[Save The World With Code](https://www.mhprofessional.com/9781260457599-usa-save-the-world-with-code-20-fun-projects-for-all-ages-using-raspberry-pi-microbit-and-circuit-playground-express-group) - Twenty fun projects for all ages using Raspberry Pi, micro:bit, and Circuit Playground Express.
```
```
=> Add Save The World With Code to Books section.

README.md
Build a snake game on the BBC micro:bit](https://www.cameronmacleod.com/blog/microbit-snake) - A detailed tutorial walking through the steps of writing a snake game in MicroPython.
```
```
=> Add Build a snake game on the BBC micro:bit to Articles section.

README.md
[pin:out](https://microbit.pinout.xyz) - A GPIO pinout interactive reference for the BBC micro:bit and accessories.
```
```
=> Add pin:out to Miscellaneous section.

README.md
[micro:bit Firmware](https://microbit.org/get-started/user-guide/firmware/) - General information about the firmware with instructions on how to update it to the latest version.
```
```
=> Add micro:bit Firmware to Interface Chip section

README.md
[timeanddate](https://github.com/bsiever/microbit-pxt-timeanddate) -  Software Based Real Time Clock (Time & Date) for the micro:bit.
```
```
=> Add timeanddate to PXT Extensions

README.md
[MakeCode Multi Editor](https://makecode.microbit.org/---multi) - Two editors side by side to create, modify, and test two programs at the same time. Great for running micro:bit radio programs with a transmitter and receiver.
```
```
=> Add MakeCode Multi Editor to Visual Programming.

README.md
[micro:bit & Vital Signs](https://medium.com/liki-blog/micro-bit-vital-signs-b76e495f6a59) - How to measure pulses in the micro:bit to build a pulse monitor and the measurement device with an optical heart rate detector.
```
```
=> Add micro:bit & Vital Signs to Articles section.

README.md
[Measuring pendulum decay with BBC micro:bit and XinaBox](https://www.hackster.io/PragmaticPhil/measuring-pendulum-decay-with-bbc-micro-bit-and-xinabox-b836a2) - Collecting large data sets is key to applied data science, use the techniques in this project to collect data on your BBC micro:bit.
```
```
=> Add Measuring pendulum decay with BBC micro:bit and XinaBox to Articles.

README.md
[Smart Garden Ornaments](https://github.com/jimbobbennett/smart-garden-ornaments) - Track things happening in your garden, neighbourhood or school using smart garden ornaments with the BBC micro:bits, Raspberry Pi, and a cloud-based IoT service.
```
```
=> Add Smart Garden Ornaments to Projects.

README.md
[MakeCode Streamer Beta](https://makecode.com/streamer/docs) - Experimental web app that simplifies the creation of interactive, high quality coding videos. Designed for teachers, students or generally anyone who would want to do any kind of online MakeCode coding.
```
```
=> Add MakeCode Streamer Beta.

README.md
- [Code with Liam](https://www.youtube.com/channel/UCubWM52hsTe2eeiTWqRJICw/) - Video tutorials showing how to code with the micro:bit.
```
```
=> Add Coding with Liam to Videos

README.md
[NCCE KS3 Physical computing](https://teachcomputing.org/curriculum/key-stage-3/physical-computing) - This unit applies and enhances the learners’ programming skills in a new engaging context: physical computing, using the BBC micro:bit.
```
```
=> Add NCCE KS3 Physical Computing to Teaching.

README.md
Added are two very useful spotify-node-microbit projects and a handy MakeCode extension with different proejcets on.
The extension is still in development and I'm adding new projects quite often.
I think the community would really like these additions though
```
```
=> Add projects/extensions

README.md
[Beginning Data Science, IoT, and AI on Single Board Computers](https://www.apress.com/gp/book/9781484257654) - Core Skills and Real-World Application with the BBC micro:bit and XinaBox.
```
```
=> Add Beginning Data Science to Books.

README.md
- [Testing the micro:bit's ADC](http://www.doctormonk.com/2020/08/testing-microbits-analog-inputs.html) - The micro:bit can measure analog voltages, but you can't measure something without altering it & the best we can do is to make the measurement errors small. This article determines the micro:bit ADC measurement error.
```
```
=> Add Testing the micro:bit's Analog Inputs to Articles.

README.md
[micro:bit subreddit](https://www.reddit.com/r/microbit/)
```
```
=> Add subreddit to Community section.

README.md
[Delightfully Delirious Day Clock](https://www.hackster.io/8bitsandabyte/delightfully-delirious-day-clock-b8cd6c) - Also wondering what day it is today? This delightfully delirious day clock narrows it down to roughly eight different possibilities.
```
```
=> Add Delightfully Delirious Day Clock to Projects.

README.md
[Remote Learning with micro:bit](https://www.sparkfun.com/news/3304) - Webinar showing how to remotely teach students all about micro:bit in less than one hour.
```
```
=> Add Remote Learning with micro:bit to Teaching Resources.

README.md
[micro:bit Air Guitar](https://www.instructables.com/Microbit-Air-Guitar-DMP/) - How to make your very own customisable guitar controller paired with micro:bit.
```
```
=> Add micro:bit Air Guitar to Projects.

README.md
[Simple gimbal with micro:bit and 2 servos](https://www.instructables.com/Simple-Gimbal-With-Microbit-and-2-Servos/) - How to make a simple gimbal stabiliser controlled by the micro:bit.
```
```
=> Project: Simple gimbal with micro:bit and 2 servo.

README.md
[The Tinkerer's Guide to the micro:bit Galaxy](https://gethacking.com/products/the-tinkerers-guide-to-the-micro-bit-galaxy) - Get ready to make and code amazing projects that light up, make noise, move, and talk (via radio).
```
```
=> Books: The Tinkerer's Guide to the micro:bit Galaxy

README.md
Hey @carlosperate 
just a typo...
Cheers!
=> Removing double "the"

README.md
- [Make your own processor with a micro:bit](http://www.suppertime.co.uk/blogmywiki/2020/05/microbit-cpu/) - Coding a 5-bit CPU in the micro:bit, useful for understanding or teaching how CPUs and simple systems work.
```
```
=> Article: Make your own processor with a micro:bit.

README.md
[DF Robot micro:bit blog section](https://www.dfrobot.com/blog-tag-micro:bit.html) - Blog posts and articles about micro:bit from DF Robot.
```
```
=> Article Collections: Restore DF Robot micro:bit blog section.

README.md
[Disaster Management with Smart Circuit Breaker](https://blog.adacore.com/make-with-ada-2020-disaster-management-smart-circuit-breaker) - Ensuring safety against electrical fire or shock during earthquake, flood, gas leakage & fire breakout by disconnecting mains with smart circuit breaker.
```
```
=> Project: Add Disaster Management with Smart Circuit Breaker.

README.md
- [Coding with micro:bit video series for teachers](https://www.youtube.com/playlist?list=PLmqeu38gRdJVCMUhgmF8OrjOhYpYtoh9U) - Videos series resource for teachers and students with an introduction to coding with micro:bit to build inventions and make creations integrating LEDs, motors, servos and speakers.
```
```
=> Teaching: Add Coding with micro:bit video series for teachers.

README.md
- [micro:bit Corona Scanner](https://github.com/znuh/microbit-corona-scanner) - Using a micro:bit to listen to Bluetooth COVID-19 Exposure Notifications from COVID mobile apps.
```
```
=> Project: micro:bit Corona Scanner.

README.md
[SmartMatrix](https://github.com/Shorts1999/pxt-smartmatrix) - Easily control LED matrices/displays made from ws2812b/NeoPixel controllable RGB LEDs.
```
```
=> MakeCode: Add SmartMatrix extension.

README.md
- [micro:bit LIVE 2020 virtual](https://microbit.org/news/events/live/) - Join educators, researchers, and the developer community for micro:bit LIVE 2020 virtual, an online event this Friday and Saturday!
```
```
=> Add micro:bit LIVE 2020 virtual to Events

README.md
[Python For Kids](https://github.com/mytechnotalent/Python-For-Kids) - A comprehensive online Python development course for kids utilizing a BBC micro:bit and later an ESP32 board going step-by-step into the world of Python for microcontrollers.
```
```
=> Teaching: Add Python for Kids.

README.md
[Bare metal examples](https://github.com/dwelch67/microbit) - C bare metal examples for the BBC micro:bit.
```
```
=> C/C++: Add bare metal examples.

README.md
[Zig](https://github.com/markfirmware/zig-bare-metal-microbit) - A BBC micro:bit bare metal example in the Zig language.
```
```
=> Other Languages: Add Zig example.

README.md
[micro:Maqueen Library for Arduino](https://github.com/kd8bxp/micro-Maqueen-Arduino-Library) - A simple Arduino library for the DF Robot micro:Maqueen robot, using a BBC Micro:Bit controller.
```
```
=> C/C++ Libraries: Add micro:Maqueen Library for Arduino.

README.md
[Bluetooth Mouse](https://github.com/kshoji/pxt-bluetooth-mouse) - MakeCode extension for BLE HID Mouse module for micro:bit.
```
```
=> MakeCode Extension: Add Bluetooth Mouse.

README.md
[Voice activated Micro:bit with Machine Learning](https://www.edgeimpulse.com/blog/voice-activated-microbit) - How to make your micro:bit respond to a keyword, by training a machine learning model with Edge Impulse that recognizes your voice.
```
```
=> ML: Add Voice activated micro:bit with Machine Learning

README.md
[Hands-Free Cardboard Gumball Machine](https://www.instructables.com/Hands-Free-Cardboard-Gumball-Machine/) - A gumball machine using a micro:bit, Crazy Circuits Bit board, distance sensor, servo, and cardboard. It detects when you place your hand in the base of the rocket and the machine administers a gumball, without touching a thing.
```
```
=> Projects: Add Hands-Free Cardboard Gumball Machine.

README.md
[Vibrational Anomaly Detection](https://github.com/Technica-Corporation/microbit-ml) - This project introduces a statistics-based, time-series Vibrational Anomaly Detection using Tri-Axial cccelerometer data on a micro:bit.
```
```
=> ML: Add Vibrational Anomaly Detection.

README.md
[Automatic Plant Watering System Using a micro:bit](https://www.instructables.com/Automatic-Plant-Watering-System-Using-a-Microbit/) - How to build an automatic plant watering system using a micro:bit, moisture sensor, and some other small electronic components.
```
```
=> Projects: Automatic Plant Watering System Using a micro:bit

README.md
[micro:bit LIVE 2020 virtual](https://www.youtube.com/playlist?list=PLEo0hMrjdofv9-M0IOyD8Q0VtsX8O__iW) - All the talks and sessions from the micro:bit LIVE 2020 Virtual online event.
```
```
=> Add micro:bit LIVE 2020 virtual to Conference Talks

README.md
[Sorting the Object Using Ferb Detective Agent](https://www.instructables.com/Sorting-the-Object-Using-Ferb-Detective-Agent/) - How to design a DIY colour sorter that can sort black and white objects using an IR sensor.
```
```
=> Projects: Add Sorting the Object Using Ferb Detective Agent.

README.md
- [BBC micro:bit V2 - Workshop Webinar](https://www.element14.com/community/events/5668/l/bbc-microbit-v2-workshop-webinar) - Get to know the BBC micro:bit V2 in this "box to first project" workshop webinar on January 14th and ask questions of the team that made it happen! 
```
```
=> Events: Add BBC micro:bit V2 - Workshop Webinar.

README.md
[micro:bit Solar Tracker](https://www.instructables.com/Microbit-Solar-Tracker/) - How to build a solar tracker with a micro:bit, light sensors and servos.
```
```
=> Projects: Add micro:bit Solar Tracker.

README.md
[DreamSpace TV](https://education.microsoft.com/en-us/resource/f7b52fd4) - Lessons to bring students, in school or at home, on a STEAM learning journey with a focus on computational thinking, creativity & problem-solving.
```
```
=> Teach: Add DreamSpace TV for secondary schools.

README.md
[MicroJIT](https://github.com/thomasdenney/microjit) - A Just-In-Time compiler for [Alex Roger's Stack Virtual Machine](http://www.cs.ox.ac.uk/people/alex.rogers/stack/) on the BBC micro:bit.
```
```
=> Other Langs: Add MicroJIT.

README.md
- [Bluetooth Keyboard](https://github.com/kshoji/pxt-bluetooth-keyboard) - MakeCode extension for BLE HID Keyboard module for micro:bit.
- [Bluetooth Gamepad](https://github.com/kshoji/pxt-bluetooth-gamepad) - MakeCode extension for BLE HID Gamepad module for micro:bit.
```
```
=> MakeCode: Add Bluetooth Keyboard and Gamepad.

README.md
[AlpacaML](https://github.com/LaboratoryForPlayfulComputation/AlpacaML) - Automated Learning and Prototyping for Athletics and Creative Activity with Machine Learning. A wearable micro:bit connected to an app that can graph the data and learn to classify actions based off of the users criteria.
```
```
=> Machine Learning: Add AlpacaML

README.md
Micro:bit Educational Foundation on YouTube](https://www.youtube.com/channel/UCJRGTnzeb0esPmsE-mFkPGg/)
```
```
=> Community: Add official YouTube channel.

README.md
[Introduction to the micro:bit V2 Webinar](https://webinars.nordicsemi.com/introduction-to-the-microbit-v2/) - In this webinar on 3rd of February, Jonny Austin, CTO of The Micro:bit Educational Foundation will talk about the features of the new device and how they have been exposed in easy to use, web-based editors.
```
```
=> Events: Add Introduction to the micro:bit V2 Webinar

README.md
[What’s a Microcontroller? with Python and micro:bit](https://www.parallax.com/whats-a-microcontroller-with-python-and-microbit/) - Informational Zoom meeting on February 23rd (part 2 on March 23rd) for any middle school and high school educator using the micro:bit and Python, electronics, sensors and microcontrollers.
```
```
=> Events: What’s a Microcontroller? with Python and micro:bit on February 23rd

README.md
[Get started with the micro:bit](https://www.youtube.com/playlist?list=PLEo0hMrjdofusveMscRFN9FeqKzDBzuXr) - A set of videos that will take you from first use to micro:bit expert, exploring all the features of this tiny computer.
```
```
=> Videos: Add Get started with the micro:bit.

README.md
[PET Robotic Arm](https://www.instructables.com/PET-Robotic-Arm-Microbit-Project/) - A robot arm made with a servo and recycling waste plastic.
```
```
=> Projects: Add PET Robotic Arm

README.md
[Tock](https://github.com/tock/tock/blob/master/boards/microbit_v2/README.md) - An embedded operating system designed for running multiple concurrent, mutually distrustful applications on low-memory and low-power microcontrollers, with support for the BBC micro:bit.
```
```
=> Rust: Add Tock RTOS.

README.md
[Ticklebot](https://www.jasmineflorentine.com/ticklebot) - Making a ticklish robot with a micro:bit, feel free to get creative.
```
```
=> Projects: Add Ticklebot.

README.md
Resource that Jonny pointed me to recently. Linked GitHub repo has recently been updated, so looks to be maintained. 
```
```
=> add bare metal micro:bit

README.md
[Stackable micro:bit LED Matrix Magnifier](https://www.thingiverse.com/thing:4756078) - Designed to be placed on top of the micro:bit to magnify the display, it can be combined with multiple micro:bits to create a larger screen to quadruple the LED matrix.
```
```
=> 3D Printing: Stackable micro:bit LED Matrix Magnifier

README.md
Jose notified me of this one. A nice playground for Scratch and micro:bit V1/V2
```
```
=> add mbit-more

README.md
[MicroPython For micro:bit](https://github.com/mytechnotalent/MicroPython-For-micro-bit) - A free MicroPython course designed to teach MicroPython with specific application to the micro:bit V2.
```
```
=> Teaching: Add MicroPython For micro:bit.

README.md
[Digital Measuring Roller Using micro:bit & Tinkercad](https://www.instructables.com/Digital-Measuring-Roller-Using-Microbit-Tinkercad/) - How to make a digital measuring roller with the help of a micro:bit, a rotatory encoder, a few blocks of code, and some 3D printed parts.
```
```
=> Projects: Add Digital Measuring Roller Using micro:bit & Tinkercad.

README.md
[microbit-webusb](https://github.com/bsiever/microbit-webusb) - A simpler version of a WebUSB library to interact with the micro:bit, with a good README explanation, and a demo application.
```
```
=> Interface Chip: Add microbit-webusb

README.md
MicroPal Guide - Craft your own interactive micro:bit project that responds to your voice. Create a Teachable Machine Model, load it into the MicroPal website, and control the micro:bit via Web Bluetooth.
```
```
=> Machine Learning: Add MicroPal Guide.

README.md
[MCP3008](https://github.com/ti-nspire/microbit_MicroPython_MCP3008) - Library to interface with a MCP3008 10-bit Analog-to-Digital Converter (ADC).
```
```
=> MicroPython: Add MCP3008 library.

README.md
[Hacking a Cardboard PinBall Machine](https://www.instructables.com/CardBoard-Paper-MicroBit-Pinball-Machine/) - Adding a micro:bit to a cardboard pinball kit to create a game with interactive lights, sounds, and motion.
```
```
=> Projects: Add Hacking a Cardboard PinBall Machine.

README.md
- [Ada for micro:bit Getting Started](https://blog.adacore.com/ada-for-microbit-part-1-getting-started) - How to setup an Ada development environment for the micro:bit.
```
```
=> Create Ada section with setup entry.

README.md
[Ada Drivers](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/examples/MicroBit) - Drivers for the micro:bit on-board components and instruction on how to setup the Ada development environment.
```
```
=> Ada: Add Ada Drivers.

README.md
[Ada micro:bit Examples](https://github.com/Fabien-Chouteau/microbit_examples) - Examples and tutorials for Ada on the BBC micro:bit
```
```
=> Ada: Add micro:bit Examples.

README.md
[Digital Making at Home - Staying Active](https://twitter.com/Raspberry_Pi/status/1374012549230903298) - This Wednesday (24th March), your kids can learn from @hengehall how to create a step counter with a micro:bit! A fun, easy & useful project for staying active.
```
```
=> Events: Digital Making at Home - Staying Active

README.md
[Ada for micro:bit articles](https://blog.adacore.com/ada-for-microbit-part-2-push-buttons) - ([Part 3](https://blog.adacore.com/ada-for-microbit-part-3-pin-output), [Part 4](https://blog.adacore.com/ada-for-microbit-part-4-pin-input), [Part 5](https://blog.adacore.com/ada-for-microbit-part-5-analog-output), [Part 6](https://blog.adacore.com/ada-for-microbit-part-6-analog-input), [Part 7](https://blog.adacore.com/ada-for-microbit-part-7-accelerometer), [Part 8](https://blog.adacore.com/ada-for-microbit-part-8-music)) A series of articles and tutorials about using Ada on the micro:bit.
```
```
=> Ada: Add Ada for micro:bit articles.

README.md
[Totally Useless Coffee Dispenser](https://www.instructables.com/Totally-Useless-Coffee-Dispenser/) - Designing and building a coffee dispenser with micro:bit, motors and 3D printed parts.
```
```
=> Projects: Add Totally Useless Coffee Dispenser

README.md
["High-Fivey" the Cardboard Robot](https://www.instructables.com/High-Fivey-the-Cardboard-Microbit-Robot/) - Stuck at home but still have a need to high-five someone? Make a friendly little cardboard micro:bit robot to do just that.
```
```
=> Projects: Add "High-Fivey" the Cardboard Robot

README.md
[Using the micro:bit in the Primary Classroom](https://community.computingatschool.org.uk/events/9107) - Join Magda & Aimee from the Micro:bit Educational Foundation on April 22th, as they guide you through set up and getting started with creative projects in the Primary classroom with micro:bit.
```
```
=> Events: Using the micro:bit in the Primary Classroom

README.md
[VEML6030](https://github.com/CoreElectronics/CE-PiicoDev-VEML6030-MicroPython-Module) - Library for interfacing with a VEML6030 Ambient Light Sensor via I2C.
```
```
=> Python: Add VEML6030 library

README.md
[Awaken the Force with micro:bit](https://www.okdo.com/project/awaken-the-force-with-microbit/) - For millennia people have used the force for good, evil, and just to lift things up and move them about. We have found quite a large amount of force inside the micro:bit, enough in fact to lift small, everyday objects.
```
```
=> Project: Awaken the Force with micro:bit.

README.md
[Building 3 fun projects with the micro:bit V2](https://www.nordicsemi.com/Events/2021/Webinar-microbit-May) - In this webinar on May 26 Jonny Austin, Micro:bit Foundation CTO, will guide you through building 3 fun projects with the BBC micro:bit V2, each showcasing the V2's new capabilities (e.g. microphone and sound).
```
```
=> Events: Building 3 fun projects with the micro:bit V2

README.md
[TMP117](https://github.com/CoreElectronics/CE-PiicoDev-TMP117-MicroPython-Module) - Library to interface with a TMP117 high precision temperature sensor.
```
```
=> MicroPython: Add TMP117 library.

README.md
[BBC micro:bit + WiFi + phone notifications](https://www.hackster.io/393644/bbc-micro-bit-wifi-phone-notifications-ddb90d) - How to connect BBC microbit to WiFi and send a phone notification when a sound is detected.
```
```
=> Projects: BBC micro:bit + WiFi + phone notifications.

README.md
- [Getting started with the micro:Bit Classroom](https://www.eventbrite.com/e/getting-started-with-the-microbit-classroom-tickets-154234777371) - A hands on, online introduction to micro:bit Classroom on June 30, learn how to setup and use it particularly when delivering the NCCE CS curriculum online.
```
```
=> Events: Getting started with the micro:Bit Classroom

README.md
[micro:bit workshop for beginners](https://www.eventbrite.co.uk/e/microbit-workshop-for-beginners-tickets-156505475089) - As part of this workshop on June 22nd, we'll introduce you to some of the amazing things you can do with the micro:bit and get you started block programming in an online classroom with a simulator.
```
```
=> Events: micro:bit workshop for beginners.

README.md
[Arm's Innovation Coffee - micro:bit](https://www.youtube.com/watch?v=N3W_auWJEac) - This Thursday join a chat with Jonny Austin, Micro:bit Foundation CTO, demoing & showing off the micro:bit V2 as well as talking about what's coming up for the pocket-sized computer!
```
```
=> Events: Arm's Innovation Coffee - micro:bit.

README.md
[BME280](https://github.com/CoreElectronics/CE-PiicoDev-BME280-MicroPython-Module) - Library to interface with a BME280 sensor measuring relative humidity, barometric pressure and ambient temperature via I2C.
```
```
=> Python module: BME280.

README.md
[Embedded Python: Build a Game on the BBC micro:bit](https://realpython.com/embedded-python/) - In this tutorial you’ll learn what embedded development is, why you would use Python, and how to write a basic game on the BBC micro:bit with MicroPython.
```
```
=> Articles: Embedded Python: Build a Game on the BBC micro:bit

README.md
[DreamSpace do your:bit camp](https://www.microsoft.com/dreamspace/UpcomingEvents/Index) - Join us for the do you:bit online camp for students aged 11 to 17 on June 17th & 18th! Introducing the Global Goals, programming with micros:bit, and the do your:bit challenge.
```
```
=> Events: DreamSpace do your:bit camp

README.md
[Scratch+micro:bit](https://plix.media.mit.edu/activities/scratch-microbit) - This activity combines storytelling, coding, and making to engage in physical tinkering while helping to bridge the gap between the physical and digital worlds with micro:bit.
```
```
=> Teaching Resources: Add Scratch+micro:bit

README.md
- [Battery Pack Holder](https://microbit.org/get-started/user-guide/battery-pack-holder/) - The new micro:bit comes with a cardboard cut out to hold the micro:bit and battery pack, this is the template to create and customise your own battery holder.
```
```
=> Misc: Add Battery Pack Holder

README.md
[micro:bit Gesture Recognizer](https://github.com/ttseng/microbit-ml) - An experimental gesture recognition tool using the Microbit's accelerometer, built using ml5js. Ml5js is built on top of TensorFlow.js.
```
```
=> ML: Add micro:bit Gesture Recognizer.

README.md
[Tinkercad Circuits](https://www.tinkercad.com/learn/circuits) - Create, code, and simulate electronic designs using common components with the micro:bit or Arduino, [related article](https://blog.tinkercad.com/explore-microbit-with-tinkercad).
```
```
=> Visual Programming: Add Tinkercad Circuits.

README.md
[MMA8653](https://github.com/lfhohmann/MMA8653) - This Arduino library brings support for the NXP MMA8653 I2C accelerometer.
```
```
=> Cpp: Add MMA8653 Arduino library.

README.md
[Solderless micro:bit timer](https://www.thingiverse.com/thing:4790928) - A configurable timer made with a v2 micro:bit board, some electronics components and very few soldering.
```
```
=> 3D Printing: Add Solderless micro:bit timer.

README.md
[Build a snake game](https://www.cameronmacleod.com/blog/microbit-snake) - Learning how to make a snake game using MicroPython on the micro:bit.
```
```
=> Articles: Add Build a snake game.

README.md
[Using the micro:bit to detect electrical current](https://mattoppenheim.com/2021/07/16/using-the-microbit-to-detect-electrical-current/) - The micro:bit has a magnetometer on-board, when a current flows through a wire a magnetic field is produced and we can use the magnetometer to detect this.
```
```
=> Articles: Add Using the micro:bit to detect electrical current.

README.md
[Mechanical 7-segment digital clock](https://www.thingiverse.com/thing:4626956) - Digital clock with 23 segments, controlled by a single RC servo motor, with all segments and the carries between digits mechanically resolved.
```
```
=> Projects: Add mechanical 7-segment digital clock.

README.md
[ubit.js](https://github.com/lyneca/ubit.js) - Library for Node.js to interact with the on-device MicroPython file system via serial connection.
```
```
=> JS: Add ubit.js.

README.md
[microbitFs](https://github.com/microbit-foundation/microbit-fs) - TypeScript library to manipulate files inside a micro:bit MicroPython hex file.
```
```
=> JS: Add microbitFs library.

README.md
[micro:bit V2 Hardware Design](https://github.com/microbit-foundation/microbit-v2-hardware) - Schematics and bill of materials for the BBC micro:bit V2.
```
```
=> Hardware: Add micro:bit V2 Hardware Design.

README.md
[Block-based Coding for Beginners with micro:bit](https://cyber.org/events/block-based-coding-beginners-micro-bit) - A 90 min virtual workshop from CYBER.ORG on September 30th. Discover the basics of block-based coding with Microsoft MakeCode for micro: bit.
```
```
=> Events: Add Block-based Coding for Beginners with micro:bit.

README.md
[Tech Talk - Kitronik LAB:bit for BBC micro:bit](https://kitronik.co.uk/blogs/resources/tech-talk-kitronik-lab-bit-for-bbc-micro-bit) - Join Kitronik on YouTube on the 23rd September at 10:30AM GMT to take close look at the Kitronik LAB:bit Educational Platform for BBC micro:bit and a live Q&A.
```
```
=> Events: Add Tech Talk - Kitronik LAB:bit for BBC micro:bit.

README.md
[Teaching Physical Computing to 5-11 year olds](https://www.futurelearn.com/courses/teaching-physical-computing-to-5-to-11-year-olds) - Introduction to the world of physical computing with a Crumble or a BBC micro:bit, and learn how it can encourage learners to use their imaginations to solve problems and develop new ideas.
```
```
=> Online Courses: Teaching Physical Computing to 5-11 year olds.

README.md
[Mechanical digital clock](https://www.thingiverse.com/thing:4613624) - 4 digits, 24 hour-notation mechanical digital clock controlled by micro:bit and only one RC servo motor. Time adjustment from PC is possible via bluetooth.
```
```
=> Projects: Add Mechanical digital clock.

README.md
[Electronics, MicroPython, and BBC micro:bit Bootcamp](https://www.udemy.com/course/electronics-micropython-and-bbc-microbit-bootcamp/) - Learn Basics of Electronics, MicroPython, and BBC Microbit in detail in a single course.
```
```
=> Courses: Electronics, MicroPython, and BBC micro:bit Bootcamp.

README.md
[BASICtools](https://www.coridium.us/coridium/blog/basic-for-microbit) - A BASIC dialect (similar to the original Microsoft BASIC, QBASIC, or early versions of Visual BASIC) ported to the micro:bit, with provided examples.
```
```
=> Other Languages: Add BASICtools.

README.md
[Build a Physical Computing Prototype](https://www.futurelearn.com/courses/build-a-physical-computing-prototype) - On this course you’ll learn what’s inside the devices we all use every day, come to understand how they work, and ultimately learn to create your own physical computing prototype.
```
```
=> Courses: Build a Physical Computing Prototype.

README.md
[micro:bit LIVE 2021](https://microbit.org/news/events/live/) - Connect virtually on December 3rd and 4th with educators, researchers, and tech developers from around the world showcasing the latest innovations and best practice in the micro:bit community.
```
```
=> Events: Add micro:bit LIVE 2021.

README.md
Thanks for this list of cool micro:bit things!!
Added the bit:booster add-on.
- [ X] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
- [ X] I am making an individual pull request for each suggestion
- [ X] I have used the correct spelling and capitalisation for `BBC micro:bit`, `micro:bit`, and `Micro:bit Educational Foundation` (resource title could be excluded if there is a good reason)
- [ X] The content linked is in English, or it contains an English translation
- [X ] I have added the new entry to the bottom of its the category
- [ X] I have used the following format:
```
```
=> Videos: Add playlist with a wide range of videos on the micro:bit

README.md
[Lip Syncing Characters](https://www.instructables.com/Lip-Syncing-Characters-With-Microbit/) - Cute characters that lip-sync to the sound of your voice with micro:bit to appear as if they are the ones doing the talking/singing.
```
```
=> Projects: Add Lip Syncing Characters.

README.md
[ioprog Zephyr & micro:bit Articles](https://ioprog.com/tag/microbit-v2/) - A series of articles and tutorials using the micro:bit on board components with Zephyr.
```
```
=> C++: Add ioprog Zephyr & micro:bit Articles.

README.md
[Building a mini sumo robot on a budget](https://www.youtube.com/watch?v=Y9WXdobs_vU) - Designing a mini sumo robot from scratch with micro:bit. From a simple sketch on paper, to component selection, hardware design, mechanical assembly, programming, and testing.
```
```
=> Videos: Add Building a mini sumo robot on a budget.

README.md
- [OpenBlock](https://openblockcc.github.io/wiki/en/) - Block programming with hardware device support, including micro:bit, with code generation, compilation, flashing, and serial connection.
```
```
=> Visual Programming: Add OpenBlock.

README.md
[Pathfinders Professional Development Course](https://microbit.org/news/2021-12-06/microbit-lessons-for-cs-the-new-teacher-pd-course-is-launched-today/) - Created to bring the delight of physical computing to Elementary CS lessons & designed to support educators looking for ways to integrate CS into their classrooms.
```
```
=> Courses: Add Pathfinders Professional Development Course.

README.md
[micro:bit Stubs](https://github.com/oivron/microbit-stubs) - Python stubs with type hints to provide autocompletion in code editors.
```
```
=> Python tools: Add micro:bit stubs.

README.md
[OpenBeacon](https://github.com/meriac/openbeacon-ng) - Provides Active 2.4 GHz RFID Realtime Proximity and Position Tracking using the nRF51822 BLE chip, with micro:bit specific instructions.
```
```
=> Projects Utilising micro:bit: Add OpenBeacon.

README.md
[OpenHaystack](https://github.com/seemoo-lab/openhaystack) - Framework for tracking personal Bluetooth devices via Apple's massive Find My network. Build your own 'AirTags' with a micro:bit.
```
```
=> Projects Utilising micro:bit: Add OpenHaystack.

README.md
[Mirage](https://github.com/RCayre/mirage) - A powerful and modular framework dedicated to the security analysis of wireless communications.
```
```
=> Projects Utilising micro:bit: Add Mirage.

README.md
[Spy Tech](https://www.instructables.com/Spy-tech-Intruder-Detection-Logging-System/) - Intruder detection and logging system with a micro:bit and a magnet.
```
```
=> Projects: Add Spy Tech.

README.md
[MbedOS micro:bit V2 Starter](https://github.com/microbit-foundation/mbedos-microbit-v2-starter) - MbedOS template project that adds support for the micro:bit V2.
```
```
=> C++: Add MbedOS micro:bit V2 Starter.

README.md
[Strype](https://www.strype.org) - A novel tool that combines the strengths of blocks and text programming with the use of Frames. Write real Python for the micro:bit with drag and drop features.
```
```
=> Python: add Strype editor.

README.md
[LoRaWAN micro:bit](https://github.com/ribbotson/LoRaWAN_MicroBit) - This is a free open source LoRaWAN interface for BBC micro:bit including power control timer.
```
```
=> Hardware: Add LoRaWAN micro:bit.

README.md
[MakeCode and Hardware](https://www.youtube.com/channel/UCYvU-GOQCX97aDu3o4bxl_Q/videos) - YouTube channel with a large collection of projects using micro:bit and MakeCode.
```
```
=> Videos: Add MakeCode and Hardware.

README.md
[The Engineering Design Process](https://www.youtube.com/playlist?list=PLCUVFFwr4MKe_qkWNozMlhvm5GJLzjjsD) - Jasmine is here to take you though the stages of planning, designing and building your micro:bit project following the engineering design process.
```
```
=> Videos: Add The Engineering Design Process playlist.

README.md
Added the micro:bit LIVE 2021 conference and reworded some of the conference talks section
I added the link to this year(2021)'s micro:bit live conference
```
```
=> Update Conference Talk section

README.md
[micro:bit Video](https://github.com/blogmywiki/microbit-video) - C++ programs for generating NTSC video from a V1 micro:bit to connect to a TV.
```
```
=> C++: Add micro:bit Video.

README.md
[What’s a Microcontroller? with Python and micro:bit](https://www.parallax.com/whats-a-microcontroller-with-python-and-microbit-zoom-meeting-part-2/) - Workshops for educators on April 25, 27 and 29 to add a pre-engineering focus and to support career technology education (CTE) programs in coding, product design, and manufacturing.
```
```
=> Events: What’s a Microcontroller? with Python and micro:bit

README.md
- [Docker micro:bit Toolchain](https://github.com/carlosperate/docker-microbit-toolchain) - Docker image with the micro:bit toolchain, useful to easily compile C/C++ programmes like DAL & CODAL (the micro:bit runtime), MicroPython, DAPLink, etc.
```
```
=> Programming Tools: Add Docker micro:bit Toolchain.

README.md
[micro:bit OLED Game](https://www.instructables.com/Microbit-OLED-Game/) - Creating a Game & Watch homage handheld electronic game with a micro:bit, OLED screen, buttons, and MicroPython.
```
```
=> Projects: Add micro:bit OLED Game.

README.md
[LIVE code-a-long with micro:bit](https://www.eventbrite.co.uk/e/live-code-a-long-with-microbit-making-a-password-generator-tickets-266654911017) - Join this exciting code-a-long with micro:bit on the 2nd of March, and code your very own password generator (micro:bits not required).
```
```
=> Events: Add LIVE code-a-long with micro:bit.

README.md
[Water Rocket](https://wikifactory.com/+fablabbratislava/a-microbit-water-rocket/) - Did you know you can create your own water rocket by using water pipes and a water bottle? You can even add a micro:bit and measure flight data, which can be stored and later visualised.
```
```
=> Projects: Add Water Rocket.

README.md
[The Discovery book](https://docs.rust-embedded.org/discovery/microbit/) - This book is an introductory course on microcontroller-based embedded systems, using micro:bit, that uses Rust as the teaching language rather than the usual C/C++.
```
```
=> Rust: Add The Discovery book.

README.md
[Sumo Robot](https://github.com/hansj66/micro-bot) - Firmware and hardware design files for the TimeExpander.com micro:bit based robot with 2 motor bridges, 3 time of flight sensors, 4 reflective object sensors, and a GPIO Expander.
```
```
=> Hardware: Add Sumo Robot.

README.md
[PC micro:bit MicroPython](https://pc-microbit-micropython.readthedocs.io/en/latest/introduction/introduction.html) - Lessons to help you code your micro:bit using MicroPython.
```
```
=> Teaching resources: Add PC micro:bit MicroPython.

README.md
[Hardware to browser communication](https://www.youtube.com/watch?v=gqA1xbsCOjk) - Web connecting hardware with Zephyr (RTOS), LitElement (Web Components), and a micro:bit.
```
```
=> Conference Talks: Add Hardware to browser communication.

README.md
[microbit-dal-ext-kit](https://github.com/softgraph/microbit-dal-ext-kit) - A set of components and utilities for C++ applications using micro:bit DAL (runtime).
```
```
=> C/C++: Add microbit-dal-ext-kit.

README.md
[panQuad](https://www.prusaprinters.org/prints/135495-panquad) - Quadruped robot powered by the micro:bit, a robot:bit, and 8 servo motors.
```
```
=> 3D Printing: Add panQuad.

README.md
[Tilting LEGO Maze](https://www.instructables.com/Tilting-LEGO-Maze-With-Microbit/) - A LEGO maze with knobs on two of the sides to allow you to tilt and manoeuvrer a ball through the maze. You can design your own mazes (it's LEGO!) so you can make them as easy or difficult as you wish.
```
```
=> Projects: Add Tilting LEGO Maze.

README.md
[bitbotxl](https://github.com/oivron/bitbotxl) - Module for the 4tronix Bit:Bot XL Robot for BBC micro:bit.
```
```
=> Python: Add module for Bit:Bot XL.

README.md
[Fab Connect](https://beta.tfabconnect.com/en/) - Online tool & dashboard to bridge multiple micro:bits together via the internet using a WebUSB connection to the browser.
```
```
=> Tools: Add Fab Connect.

README.md
[Kasper's micro:bit](https://github.com/janickr/kaspersmicrobit) - A Python package to connect to the Bluetooth LE GATT services of paired BBC micro:bit devices. Use your micro:bit as a wireless game controller! 
```
```
=> Added Kasper's micro:bit

README.md
[Barefoot meets micro:bit](https://www.computingatschool.org.uk/news-and-blogs/2022/march/barefoot-meets-the-microbit) - Barefoot Computing latest set of resources, teamed up with the Micro:bit Foundation, to create two activities with an outdoors theme and making cross-curricular links to science.
```
```
=> Teaching Resources: Add Barefoot meets micro:bit.

README.md
[micro:bit Poster](https://community.element14.com/learn/learning-center/stem-academy/microbit/m/files/2028) - Element14 has put together this detailed, beautifully rendered, cross-section micro:bit poster highlighting all of the device's key functions and components.
```
```
=> Misc: Update Element 14 micro:bit poster for V2.

README.md
[micro:bit Professional Development Courses](https://microbit.thinkific.com/) - Designed to take the stress out of your computing responsibilities. They are aimed at teachers and educators supporting primary/elementary students.
```
```
=> Teaching Resources: micro:bit Professional Development Courses.

README.md
[How to integrate micro:bit across the primary curriculum](https://us02web.zoom.us/webinar/register/WN_sYr6KWaFTg2TZPUYyjfX2w) - Teacher session on June 8th to broaden their micro:bit experience. We’ll provide ideas and inspiration for cross curricular work and show you where to find the resources to support you.
```
```
=> Events: Add How to integrate micro:bit across the primary curriculum.

README.md
[Student code-alongs](https://microbit.org/news/events/webinars/) - On June the 15th or 29th you and your class can join a LIVE micro:bit coding session with other classes from across the UK, to make a fun summer activity picker.
```
```
=> Events: Add Student code-alongs.

README.md
[Companion Bot](https://microbit.hackster.io/laurentnaegelen/companion-bot-for-jr-steam-91221f) - A cute and interactive shoulder pet robot for Jr STEAM kids from 7 years old. Sewing, 3D printing, electronics, software and it's all open source.
```
```
=> Projects: Add Companion Bot.

README.md
[micro:bit V2 Pager](https://devzone.nordicsemi.com/nordic/nordic-blog/b/blog/posts/micro-bit-v2-pager) - This blog post shows how to make a one-way BLE pager with a micro:bit V2 and nRF Connect SDK, to send text messages to the micro:bit using your smartphone or tablet.
```
```
=> Articles: Add micro:bit V2 Pager.

README.md
[The Instant Star Guitar](https://learn.browndoggadgets.com/Guide/The+Instant+Star+Guitar/441) - Play thousands of rock songs with the press of a button on this electric instant rock star micro:bit guitar.
```
```
=> Projects: Add The Instant Star Guitar.

README.md
[Cybersecurity with Python & micro:bit](https://www.parallax.com/cybersecurity-with-python-microbit-three-session-educators-workshop-august-22-24-26-2022/) - Online workshop in August for Educators in the USA. Explore and apply basic cybersecurity concepts with physical computing on micro:bit, utilizing Python and radio communication.
```
```
=> Events: Add Cybersecurity with Python & micro:bit.

README.md
[Escape Room micro:bit - Magic Tune](https://microbit.hackster.io/VBB/escape-room-micro-bit-1-magic-tune-0f8552) - Code the micro:bit to play the magic tune exactly as the forest fairy demands to make your escape.
```
```
=> Projects: Add Escape Room micro:bit - Magic Tune.

README.md
[NCCE KS2 Sensing movement](https://teachcomputing.org/curriculum/key-stage-2/programming-b-sensing) - Final KS2 programming unit that brings together elements of all previously covered programming constructs in a different, but familiar environment, with the micro:bit.
```
```
=> Teaching Resources: Add NCCE KS2 Sensing movement unit.

README.md
[Machine Learning Dance Move Detector](https://www.okdo.com/project/machine-learning-dance-move-detector/) - Builds a system running on the micro:bit which can identify TikTok dance routines using the onboard accelerometer.
```
```
=> ML: Add Machine Learning Dance Move Detector.

README.md
[micro:bit code-along 29th of November](https://www.computingatschool.org.uk/events/2022/november/microbit-code-along-health-and-wellbeing) - Know how to use the micro:bit to explore the 5 ways of wellbeing, develop a nature counter, send a smile, and explore other methods for use of the radio function.
```
```
=> Events: Add micro:bit code-along 29th of November.

README.md
[A micro:bit of AI](https://ai-training.glitch.me) - A tool to bridge the gap between the Teachable Machine AI and a micro:bit. Train an AI to make a prediction, and then code your micro:bit to use those predictions to activate motors, lights & more!
```
```
=> ML: Add A micro:bit of AI.

README.md
[Data logging with micro:bit](https://us02web.zoom.us/webinar/register/WN_wKZ8X7alShC_CW88G4FTag) - Webinar for teachers on the 16th of November to find out more about using the micro:bit to collect and analyse data from the world around you.
```
```
=> Events: Add Data logging with micro:bit webminar.

README.md
[Text-based coding with the new micro:bit Python Editor](https://us02web.zoom.us/webinar/register/WN_tLClPjewQeaeIRoPqf1txA) - Webinar on the 10th of November, using the new micro:bit Python Editor to teach text-based coding, with resources and tips for taking Python teaching further.
```
```
=> Events: Add Text-based coding with the new micro:bit Python Editor webinar

README.md
[Text-based coding with the new micro:bit Python Editor](https://us02web.zoom.us/webinar/register/WN_XI-7-vE0Q7mZG1FRQdB9mw) - Webinar on the 15th of November, using the new micro:bit Python Editor to teach text-based coding with hands-on activities, resources and tips for taking Python teaching further.
```
```
=> Events: Add Text-based coding with the new micro:bit Python Editor.

README.md
[micro:bit AI vehicle](https://microbit.hackster.io/lillian-brevik/micro-bit-ai-vehicle-3051f5) - A voice to controlled micro:bit vehicle using a Web App that recognizes 5 words and connects to the micro:bit via Web Bluetooth.
```
```
=> ML: Add micro:bit AI vehicle.

README.md
[BBC micro:bit in Practice](https://www.packtpub.com/product/bbc-microbit-in-practice/9781804610121) - A hands-on guide for building creative real-life projects with MicroPython and BBC micro:bit.
```
```
=> Literature: Add BBC micro:bit in Practice.

README.md
[Low cost solar power source for micro:bit](https://microbits-projects.blogspot.com/2022/09/low-cost-solar-power-source-for.html) - A low-cost DIY solar power source aimed at school projects such as weather stations, to log readings at intervals, and upload them to a computer for analysis.
```
```
=> Projects: Add Low cost solar power source for micro:bit.

README.md
[The Invent To Learn Guide to the micro:bit](https://cmkpress.com/product/microbit/) - Create dozens of simple-to-complex, open-ended, hands-on projects using one or more micro:bits, upcycled junk, and craft supplies.
```
```
=> Books: add The Invent To Learn Guide to the micro:bit.

README.md
[Code.org CS Fundamentals](https://code.org/maker/csf-microbit) - BBC micro:bit resources for CS Fundamentals. Each course has a guide containing everything needed to use the micro:bit to add the immersive power of physical computing to your teaching of Code.org’s CS Fundamentals Course.
```
```
=> Teacher Resources: Add Code.org CS Fundamentals micro:bit resources.

README.md
[Code Along, Networks and Radio Comms](https://blogs.glowscotland.org.uk/glowblogs/digilearn/2023/02/06/3rd-march-11-1145am-code-along-networks-and-radio-communication-with-microbit-second-level-learners/) - In tomorrow's live lesson, we'll send messages between two or more micro:bits and use a simple encryption to protect them.
```
```
=> Add Code Along, Networks and Radio Comms.

README.md
[micro:bit Python Editor](https://kitronik.co.uk/blogs/resources/tech-talk-micro-bit-python-editor-thurs-9th-march-10-30am) - Kitronik Tech Talk on the 9th of March to explore the basics of using the 🆕 micro:bit Python Editor. They'll explore the interface and get hands on with some simple code and examples.
```
```
=> Add Kitronik Tech Talk micro:bit Python Editor event.

README.md
[Getting started with micro:bit for teachers](https://microbit.org/news/events/webinars/#getting-started-with-micro:bit-for-teachers) - Webminar on March 28th, a beginners guide to using micro:bit in the primary classroom. If you are a teacher wanting to introduce physical computing for the first time, this is the session for you.
```
```
=> Add Getting started with micro:bit for teachers Webminar.

.github/workflows/allow-list.txt, README.md
[Synced NeoPixel Mickey Mouse Ears](https://community.element14.com/challenges-projects/element14-presents/project-videos/w/documents/27785/episode-567-synced-neopixel-mickey-mouse-ears) - These light-up Mickey Ears made with micro:bit and neopixels, show colourful animations and sync with other ear hats for the ultimate Disney group attire.
```
```
=> Projects: Add Synced NeoPixel Mickey Mouse Ears.

README.md
[Character Design with micro:bit](https://scientiffic.medium.com/character-design-with-microbit-51c42586caa1) - Exploring how to display emotion on the micro:bit 5x5 LED matrix for character design.
```
```
=> Articles: Character Design with micro:bit.

README.md
[Coding for Your Classroom 4 - 10](https://www.edx.org/course/coding-for-your-classroom-4-10) - Course to build educators’ comfortability and confidence in digital literacy, through hands-on learning activities and demos in a variety of web-based platforms, including micro:bit.
```
```
=> Professional Development: Coding for Your Classroom 4 - 10.

README.md
[Intermediate Coding with micro:bit](https://csinschools.io/courses/intermediate-coding-with-microbit/) - CS in Schools materials with micro:bit designed to help teachers confidently deliver a fun, engaging, and industry-relevant programme.
```
```
=> Teaching Resources: Intermediate Coding with micro:bit.

README.md
[Coding with BBC micro:bit in easy steps](https://ineasysteps.com/products-page/coding-with-bbc-microbit/) - Teaches children how to use the BBC micro:bit, and guides them through 10 exciting projects designed to make learning fun.
```
```
=> Books: Add Coding with BBC micro:bit in easy steps.

README.md
[micro:bit code-along - You've got this!](https://www.computingatschool.org.uk/events/2023/july/microbit-code-along-youve-got-this) - Code along on the 5th of July to create your first micro:bit programmes, learn about its sensors and input/outputs & find effective ways to teach using established pedagogic approaches.
```
```
=> Events: Add micro:bit code-along - You've got this!

README.md
[Code.org micro:bit Curriculum](https://code.org/maker/microbit) - Code.org has partnered with the Micro:bit Educational Foundation to offer teachers several resources on using the BBC micro:bit device.
```
```
=> Teach: Add Code.org micro:bit Curriculum.

README.md
[Create interactive games using MicroPython and electronics](https://www.youtube.com/watch?v=teALLngESw0) - Let's learn how to use electronics and programming to create games using MicroPython and a micro:bit board.
```
```
=> Conferences: Add Create interactive games using MicroPython and electronics

README.md
[ML-Machine](https://ml-machine.org) - An interactive machine-learning platform, utilising the micro:bit sensors to generate data, train a model, and run the model with real time sensor data streamed from the micro:bit via Bluetooth.
```
```
=> Machine Learning: Add ML-Machine.

README.md
[Hagrid's Interactive Lantern and Magic Wand](https://www.instructables.com/Hagrids-Interactive-Lantern-and-Magic-Wand-With-Ti/) - Using 3D printing, micro:bit and Tinkercad software to create your own magic wand and Hagrid's lantern, bringing the magic of Harry Potter to life.
```
```
=> Projects: Add Hagrid's Interactive Lantern and Magic Wand.

README.md
[Vision Guided Explorer Robot](https://www.instructables.com/Vision-Guided-Explorer-Robot/) - A micro:bit robot with a mounted camera transmitting video to a mobile phone and controlled by a micro:bit gamepad.
```
```
=> Projects: Add Vision Guided Explorer Robot.

README.md
- [micro:bit classroom](https://classroom.microbit.org) - Run and manage live code sessions with MakeCode or Python Editor. It makes it quick and easy for teachers to share code with students, track their progress, help them debug, and save their progress.
```
```
=> Programming: Add micro:bit classroom.

README.md
[Air Quality Monitor](https://microbits-projects.blogspot.com/2023/07/air-quality-monitor.html) - Hacking the Ikea Vindriktning air quality monitor to show the sensor data on the micro:bit display.
```
```
=> Projects: Add Air Quality Monitor.

README.md
[Get started with BBC micro:bit - the next gen](https://microbit.org/teach/events/#get-started-with-bbc-micro:bit---the-next-gen-%28uk-only%29) - Webinar on the 14th of September to introduce UK teachers to the micro:bit and share the "BBC micro:bit - the next gen" campaign.
```
```
=> Events: Add Get started with BBC micro:bit - the next gen.

README.md
[micro:bit for Robotics](https://www.youtube.com/watch?v=iwaRidlm2RM) - Video introducing the BBC micro:bit, what you can can do with it, and how to use it with robots.
```
```
=> Videos: Add micro:bit for Robotics.

README.md
=> Projects: Add micro:bit Sensor Network.

README.md
=> Python Editors: Add Microbit Explorer VSCode extension.

README.md
[micro:bit Poster pack](https://microbit.org/teach/classroom-resources/microbit-posters/) - A pack of 3 posters from the Micro:bit Foundation with "What will you create?", "Yes I can", and "A labelled micro:bit".
```
```
=> Posters: Add Foundation poster pack.

README.md
[MakeCode micro:bit Tutorials](https://www.youtube.com/playlist?list=PLMMBk9hE-SerTLN2D6NiI7v7DJ78IBIAq) - Short video tutorials to get started programming the BBC micro:bit with MakeCode.
```
```
=> Videos: Add MakeCode tutorials.

README.md
[Python Editor poster](https://microbit.org/teach/classroom-resources/python-editor-poster-creativity/) - A poster of the micro:bit Python Editor illustrating its features.
```
```
=> Posters: Add Python Editor poster from the Foundation.

README.md
[`microbit_edu` on Instagram](https://www.instagram.com/microbit_edu/)
```
```
=> Community: Add Foundation Instagran account.

README.md
- [Sustainable Computing](https://www.digitall.charity/sustainablecomputing) - BBC micro:bit projects combining physical construction, coding, and environmental awareness to engage students in understanding the nature of the world around them.
```
```
=> Teach: Add Sustainable Computing.

README.md
[Out Of This World](https://www.digitall.charity/outofthisworldwiththemicrobit) - Combine BBC micro:bit coding concepts with practical applications, demonstrate the relevance of coding in various scenarios, and address the specific needs of astronauts with this set of activities.
```
```
=> Teach: Add Out Of This World.

README.md
[micro:bit Projects with Python and Single Board Computers](https://link.springer.com/book/10.1007/978-1-4842-9197-9) - Building STEAM Projects with Code Club and Kids' Maker Groups.
```
```
=> Books: Add micro:bit Projects with Python and Single Board Computers.

README.md
[HOVER:BIT Bluetooth Controller](https://github.com/JakobST1n/microbit-gamepad) - A web app for sending DPAD events to micro:bit devices over Bluetooth.
```
```
=> Tools: Add HOVER:BIT Bluetooth Controller.

README.md
[Make: AI Robots](https://www.makershed.com/products/make-ai-robots-print) - Introduces AI through exciting craft projects with a mechanical cardboard creations, fun electronic lights, motors, simple coding on a micro:bit, and then teaches how to train AI to create a spark of life.
```
```
=> Books: Add Make: AI Robots.

README.md
I have noticed some grammatical mistakes in **README** inside section "**Visual Programming**"
"**programming environment design for**"  should be "**programming environment designed for**"
Screenshot-
=> Update README.md - fix one grammar error.

README.md
[micro:bit 3D Model](https://sketchfab.com/3d-models/microbit-b453f11ad77a4545a33b3e0ecfba6fc5) - A 3D asset of the BBC micro:bit V1.
```
```
=> CAD: Add micro:bit 3D Model.

README.md
[Raspberry Pi Foundation micro:bit Project Path](https://rpf.io/microbit-intro) - BBC micro:bit Projects that focus on wellbeing, including topics like mental health, relaxation, and exercise.
```
```
=> Teach: Add Raspberry Pi Foundation micro:bit Project Path.

README.md
The [Northwestern micro:bit v2 base repository](https://github.com/nu-ce346/nu-microbit-base) contains a software environment for programming version 2.00 and 2.21 micro:bit boards in bare metal C. It utilizes the Nordic SDK (version 16) and has a Makefile system for building and loading applications. 
The repository is used for [teaching students embedded systems](https://brghena.github.io/courses/ce346/) at Northwestern University. Several [application examples](https://github.com/nu-ce346/nu-microbit-base/tree/main/software/apps) are available, although some are incomplete and have "TODO" items for educational purposes. Although the repository is specifically for my course, others could use it as a base for their own projects without any issue.
I wasn't sure which C/C++ category this …
=> Add C bare metal resource: nu-microbit-base

README.md
[WebUSB flashing tool](https://microbit.org/tools/webusb-hex-flashing/) - Tool to flash (program) any BBC micro:bit hex file using the WebUSB technology available in Chrome and Edge browsers.
```
```
=> tools: Add WebUSB flashing tool.

README.md
[micro:bit Explorer](https://microbit-explorer.ok-y.xyz) - Explore the BBC micro:bit sensor data and inputs over BLE with Web Bluetooth.
```
```
=> Tools: Add micro:bit Explorer.

README.md
[Mr Morrison's micro:bit Lessons](https://mrmorrison.co.uk/microbit/) - Starter lessons, beyond the basics, and data & sustainability, with lesson plans, worksheets,and videos.
```
```
=> Teach: Add Mr Morrison's micro:bit Lessons.

README.md
[Advent Ornament Case](https://www.printables.com/model/664681-microbit-advent-ornamet-case) - A star ornament to clip the micro:bit and its battery pack and hang it.
```
```
=> 3D Printing: Add Advent Ornament Case.

README.md
[micro:bit for Beginners](https://www.youtube.com/watch?v=s_tTJGW98Ok) - A 2-hour educator workshop from Parallax with MakeCode and the Python Editor.
```
```
=> Videos: Add Parallax micro:bit for beginners workshop.

README.md
[Oak National Academy Resources](https://classroom.thenational.academy/units/sensing-beda) - Key stage 2 computing resources on sensing the world with the BBC micro:bit.
```
```
=> Teaching Resources: Add Oak National Academy Resources.

README.md
=> Add Next Gen & Playground Survey links

README.md
[Diorama](https://www.instructables.com/Microbit-Diorama/) - Instructable using the MakeyBit Adventure Board, expanding the micro:bit's functionality, to create robotic dioramas.
```
```
=> Projects: Add Dioramas.

README.md
[Interactive Lesson](https://cardboard.lofirobot.com/microbit-intro-interactive-lesson/) - An interactive lesson as a web app that communicates with the micro:bit via Web Bluetooth. It showcases the micro:bit features as a multimedia presentation exploring all the sensors, display, and more.
```
```
=> Miscellaneous: Add Interactive Lesson.

README.md
- [MakeCode blocks cut-out cards](https://microbit.org/teach/classroom-resources/microbit-makecode-blocks-cutout-cards/) - Printable MakeCode blocks for unplugged activities.
```
```
=> 2D Design: Add MakeCode blocks cut-out cards.

README.md
Changing the description and the url of mymicro:bit application.
- [v ] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
- [v ] I am making an individual pull request for each suggestion
- [v ] I have used the correct spelling and capitalisation for `BBC micro:bit`, `micro:bit`, and `Micro:bit Educational Foundation` (resource title could be excluded if there is a good reason)
- [v ] The content linked is in English, or it contains an English translation
- [v ] I have added the new entry to the bottom of its the category
- [v ] I have used the following format:
```
```
=> my micro:bit - url and description

README.md
[PlushPal](https://www.plushpal.app) - An online tool for creating interactive toys. Record custom gestures, and the micro:bit will react to them using machine learning.
```
```
=> Add PlushPal to ML editor/tool.

README.md
[MakeCode classroom assignments](https://makecode.microbit.org/online-learning) - Information on how to create classroom assignments for MakeCode with Google classroom, Microsoft Teams, and other classroom environments.
```
```
=> classroom: Add MakeCode classroom assignments.

README.md
The Twitter bot has been ported to Bluesky and all new entries to this Awesome List are automatically posted to Bluesky as well.
So, follow [![Bluesky Follow](https://img.shields.io/badge/(Bluesky)-@awesomemicrobit.bsky.social-8A2BE2?style=social&logo=bluesky)](https://bsky.app/profile/awesomemicrobit.bsky.social) on Bluesky to stay up-to-date with everything micro:bit. 📣
=> Awesome micro:bit now on Bluesky 🦋

README.md
- ~I am making an individual pull request for each suggestion~
- ~I have added the new entry to the bottom of its the category~
- ~I have used the following format:~
```
```
=> Update links to Micro:bit Educational Foundation in social media.

README.md
=> Change the url of mymicrobit app.
